### ISSUE TITLE
Jabra integration.js version 2.0 - setmmifocus - error

### ISSUE THREAD

**Issue by Samcotech** [gnaudio/jabra-browser-integration#43] opened 2019-09-09 11:34 UTC
We ae using Jabra Evolve 20.

We integrate successfuly. Thorugh Amzon Jabra Integration also Done. 
But we are not getting Chart graph in our site. Also in your demo site 
also. 
I did Amazon Jabara Integration as per your Documentation. But When I 
was try with your demo link. In that Chart Graph of voice background 
not display. Some JS error is displyed. SO can you please sort it out 
what was the issues and how to resolve this.

**Comment by Samcotech** [comment] 2019-09-09 11:35
I did Amazon Jabara Integration as per your Documentation. But When I 
was try with your demo link. In that Chart Graph of voice background 
not display. Some JS error is displyed. SO can you please sort it out 
what was the issues and how to resolve this.

**Comment by extmchristensen** [comment] 2019-09-09 12:07
As noted in the example, you need to use a [Jabra Engage 50](https://www.jabra.com/business/office-headsets/jabra-engage/jabra-engage-50) device for analytics to show. Basic call control should work though with Evolve 20.

For reference:
What exact chart is missing (background noise?) ? 
What exact JS error is displayed ?

**Comment by Samcotech** [comment] 2019-09-09 13:03
What exact chart is missing (background noise?) ?
ANS : Yes Both graph is missing. 1. Background Noise and 2. Audio Exposure

JS ERROR :
jabra.browser.integration-2.0.js:268 
Got error: Error: setmmifocus

**Comment by extmchristensen** [comment] 2019-09-09 13:18
Can you try again with the reuired device (Jabra Engage 50) for analytics ?

**Comment by Samcotech** [comment] 2019-09-09 13:25
We don't have that Jabra ENgage 50 Device. We are using only Jabra Evolve 20

**Comment by extmchristensen** [comment] 2019-09-09 13:29
Than the charts won't work for you. I am closing this issue, as the example charts are stated to work only with Engage 50. So not a bug.

**Closed by extmchristensen** 2019-09-09 13:29 UTC
